"""
Domain models for the CV History feature.

Each record represents one completed CV enhancement job, linking the
user to the enhanced CV JSON, the PDF S3 key, and the matching score.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class CVHistorySummary(BaseModel):
    """Lightweight projection used in list views (no JSON payload)."""

    id: UUID
    job_title: Optional[str] = Field(default=None, description="Target job title.")
    company_name: Optional[str] = Field(default=None, description="Target company.")
    matching_score: Optional[int] = Field(
        default=None, ge=0, le=100, description="ATS fit score from 0 to 100."
    )
    created_at: datetime


class CVHistoryEntry(BaseModel):
    """Full history record including the enhanced CV JSON payload."""

    id: Optional[UUID] = Field(
        default=None, description="Auto-generated by the database on insert."
    )
    user_id: UUID = Field(description="Owner's Supabase auth user UUID.")
    job_title: Optional[str] = None
    company_name: Optional[str] = None
    jd_text: Optional[str] = Field(
        default=None, description="Original job description text."
    )
    matching_score: Optional[int] = Field(default=None, ge=0, le=100)
    enhanced_cv_json: Optional[Dict[str, Any]] = Field(
        default=None, description="Serialised CVResumeSchema from the AI enhancer."
    )
    pdf_s3_key: Optional[str] = Field(
        default=None, description="S3 object key of the rendered enhanced CV PDF."
    )
    missing_skills: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Skill gaps identified during analysis (SkillGapDTO list).",
    )
    red_flags: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Red flags identified during analysis (RedFlagDTO list).",
    )
    created_at: Optional[datetime] = Field(
        default=None, description="Populated by the database on insert."
    )
